version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: perf_audit_mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017
    networks:
      - db_network

  perf_audit:
    image: audit:latest
    container_name: perf_audit
    build:
      context: .
      args:
        - node_env
    ports:
      - 3000:3000
    volumes:
      - .:/oddle
    networks:
      - db_network
    restart: on-failure

networks:
  db_network:
